FROM ubuntu:16.04

MAINTAINER Julien Corioland, @jcorioland, Microsoft

# expose port 22 for SSH
EXPOSE 22

# update
RUN apt-get update && apt-get -y upgrade

# install dependencies
RUN apt-get install -y python3-pip build-essential python3-dev libssl-dev libffi-dev

# install Azure CLI 2.0
RUN pip3 install azure-cli --upgrade

# create sym link to python
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install kubectl
RUN az acs kubernetes install-cli